#!/bin/bash
gcc -std=c++11 -c -fPIC -O2 LinuxSpriteFontPlusNative.cpp -o LinuxSpriteFontPlusNative.o
gcc -O2 LinuxSpriteFontPlusNative.o -o libSpriteFontPlusNative.so -shared
rm LinuxSpriteFontPlusNative.o
if [ ! -d ./x64/Linux ] ; then
    mkdir -p ./x64/Linux
fi
mv ./libSpriteFontPlusNative.so ./x64/Linux/libSpriteFontPlusNative.so
