<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>SpriteFontPlus</RootNamespace>
    <AssemblyName>SpriteFontPlus</AssemblyName>
    <Nullable>enable</Nullable>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <NoWarn />
    <WarningsAsErrors>;NU1605;8602;8604;8603</WarningsAsErrors>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
  </PropertyGroup>
</Project>